### ISSUE TITLE
Create Logo Design

### ISSUE THREAD

**Issue by athix** [AeonSplice/aeonsplice#22]
aka, find someone I can pay a bucket of cash for a good logo.

If you are this person, let me know. I have a bucket of cash just waiting.

**Comment by athix** [comment]
Possible solution found: www.designcrowd.com

Not quite sure what kind of budget I'm willing to allocate for a good logo, but $200 seems like a good starting place. Might bump up to $300 if I can secure myself a really good logo and all the legal rights to it. (copyright against someone stealing it)

**Comment by athix** [comment]
Currently working with a co-worker on getting a logo designed! Will close once the process is complete.

**Comment by joshbuker** [comment]
Logo is completed! :D
